spatie/laravel-ray

- src/RayServiceProvider.php
Corrected the bracketing so the host value is passed as an argument to the Client constructor rather than the binding itself
This fixes #16
> Fix setting host lost on client app binding

- src/DumpRecorder/DumpRecorder.php
- src/RayServiceProvider.php
Related to #8, this pull request adds support for Lumen.
> Add support for Lumen

- src/Ray.php
- tests/RayTest.php
I've come across various situations where I need to know if Ray is enabled or disabled. A simple example is choosing between `ray()` and `info()` for logging something in situations where something will always be logged:
```php
if (ray()->enabled()) {
ray('Received new request')->green();
} else {
info('Received new request');
}
```
By only using `ray()` the log message is lost if Ray is disabled.
Since `ray.php` lives outside of `config/`, using `config('ray.enable')` doesn't get the status (and would be prone to breaking if we had to use a config check everywhere).
The docs change is in [PR #103 in the main ray repo](https://github.com/spatie/ray/pull/103).
> Add `enabled()` and `disabled()` methods

- stub/ray.php
This changes the `ray.php` config file to use `env()` for each setting. This makes it easier for multiple developers on a project to use Ray, rather than forcing them to create their own config file. If they use Ray with default settings, it will already work. Otherwise they can tweak their config in their own `.env` as needed.
This also makes it easier to enable/disable Ray on your own local environment as needed, without having to change `ray.php` and risk accidentally committing the change.
The docs change is in [PR #104 in the main ray repo](https://github.com/spatie/ray/pull/104).
> Add `env()` vars for each Laravel config setting

- src/Ray.php
- tests/RayTest.php
This implements part of #69: allowing multiple `?Model` arguments to be passed to the `model()` method. It _doesn't_ add a `models()` method or allow an `array` or `Collection` to be passed.
> Allow multiple `?Model` arguments to be passed to `model()`

- src/Payloads/MarkdownPayload.php
- src/Ray.php
- tests/RayTest.php
- tests/__snapshots__/RayTest__it_can_render_and_send_markdown__1.json
This PR adds a the `markdown()` method, which takes a string of markdown content as its only parameter.  It renders the markdown into HTML using the `League\CommonMark` package, which is installed alongside Laravel (which is why this PR is for `spatie/laravel-ray` and not `spatie/ray`).
Some post-processing is done to ensure the resulting HTML displays correctly in Ray, such as header tags, links, and code blocks.  Only minor changes are made to make sure the output is as expected.
Unit tests have been added, and a I will be submitting a PR to `spatie/ray` with updated documentation.
> Send rendered markdown

- composer.json
- src/Payloads/LoggedMailPayload.php
- src/Ray.php
- tests/Payloads/LoggedMailPayloadTest.php
- tests/Payloads/__snapshots__/MailablePayloadTest__it_can_render_a_mailable__1.txt
- tests/RayTest.php
- tests/TestCase.php
- tests/__snapshots__/RayTest__it_can_render_and_send_markdown__1.json
- tests/resources/views/mails/test.blade.php
This adds support for headers provided with a logged mailable #47
> Add support for headers in logged mailables

- src/RayServiceProvider.php
This PR only registers singletons for the watchers in the `register()` method of the Service Provider.  The `register()` method on each watcher is called during the `boot()` method of the Service Provider.  This is done because in some instances not all dependencies were resolved during the Provider's `register()`, causing various issues.
This was submitted in relation to #137, although it may also resolve #135.
> Register watchers during Provider boot()

- src/OriginFactory.php
- src/Ray.php
- src/RayProxy.php
- src/Watchers/CacheWatcher.php
- src/Watchers/EventWatcher.php
- src/Watchers/JobWatcher.php
- src/Watchers/QueryWatcher.php
- src/Watchers/RequestWatcher.php
- src/Watchers/ViewWatcher.php
- src/Watchers/Watcher.php
- tests/TestCase.php
- tests/Unit/EventTest.php
- tests/Unit/JobTest.php
- tests/Unit/QueryTest.php
- tests/Unit/RequestTest.php
- tests/Unit/ViewTest.php
This PR allows all the color functions to be chained on all `show*` functions
```php
ray()->showQueries()->green() // all displayed queries will be displayed in a green color.
```
> Chain colours on `show*` methods

- src/Ray.php
This PR fixes an occasional bug that causes an exception to be thrown when checking the `spatie/laravel-ray` package version. In the event of an exception, it is now suppressed and a default value for the package version is used.
This should resolve issues #153, #155.
> Fix "Package spatie/laravel-ray is not installed" exception

- stub/ray.php
Fixes an issue mentioned in a comment on [this commit](https://github.com/spatie/laravel-ray/commit/7c94380be3d0ba8f98cdb8e2d060c5796460983c)
> Replace spaces with underscores in `env()` calls

- src/Watchers/ApplicationLogWatcher.php
- tests/Unit/LogTest.php
When logging, you can by accident log null. This will throw an exception in laravel-ray as it expects the message to be a string.
> Fix handling of null logs

- src/RayServiceProvider.php
In Laravel application, you can use `.env` without stubbing the configuration file (as long as application not using configuration caching).
```ini
RAY_ENABLED=(true)
SEND_REQUESTS_TO_RAY=(true)
```
In Testbench, adding the following to `phpunit.xml` will automatically configure Ray.
```xml
<server name="RAY_ENABLED" value="(true)"/>
<server name="SEND_REQUESTS_TO_RAY" value="(true)"/>
```
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> Allow to use env() when config is not available.

- src/Ray.php
- src/RayServiceProvider.php
- src/Watchers/ExceptionWatcher.php
- stub/ray.php
- tests/RayTest.php
- tests/Unit/ExceptionTest.php
This PR adds the ability to toggle the `ExceptionWatcher` class, which automatically sends exceptions to Ray.  
Specifically, it adds: 
- a `send_exceptions_to_ray` configuration setting
- a `showExceptions` method to the `Ray` class
- a `stopShowingExceptions` method to the `Ray` class
This was a feature request originally from [`spatie/ray #350`](https://github.com/spatie/ray/discussions/350).
> Enable/disable sending exceptions to Ray

- src/Watchers/ApplicationLogWatcher.php
I think it makes sense to add the red color to `critical`, `alert` and `emergency` log messages.
If you like, I could add some tests asserting that the payloads get the expected color.
I'm curious if there's a reason why color values are passed as "magic" strings, and not defined as constants like `ColorPayload::GREEN` for instance?
> Color all high severity log messages red

- src/Watchers/HttpClientWatcher.php
Hello there!
Me again. Last week I put a [PR](https://github.com/laravel/framework/pull/37597) in to Laravel to make `handlerStats` more reliable. This allows us to include native request timings and extra data like connection time and request size.
We can now remove our custom timing logic and instead get a more accurate depiction of how long the *actual request* took.
If a request is being mocked, we now also inform the user of that fact.
> Better HTTP Client logging

- src/Watchers/CacheWatcher.php
The `KeyWritten` event does not have the property minutes, nor does the parent class `CacheEvent` and as neither are macroable they check is not needed.
> Remove unnecessary property check in Cache watcher

- src/Watchers/DuplicateQueryWatcher.php
- tests/Unit/DuplicateQueryTest.php
Hi @freekmurze,
This pr will fix #217 by adding an handler for unsupported types in query parameters bindings
Also tests have been updated to address this issue
Thanks for your great work!
> Fix #217 error with duplicate queries log 

- src/Watchers/ExceptionWatcher.php
Reduce issue when `facade/ignition` is installed but not enabled.
> Check if Laravel has been bound with `Facade\FlareClient\Flare`

- stub/ray.php
When publishing the `ray.php` config file in a new project, I noticed a small typo in the file documentation.
Since the docblock I updated is about a single setting, it shouldn't use the plural "settings", but singular "setting" instead 🙂
> Fix typo in ray.php docblock

- src/DumpRecorder/DumpRecorder.php
When using Ray I noticed that Ignition stopped receiving `dump` and `dd` statements. This is because both packages replace the `VarDumper::$handler` with their own implementation and only one `$handler` can be registered at a time.
This PR makes sure the `DumpRecorder` only registers its `MultiDumpHandler` once. It also makes sure that the original `VarDumper::$handler` gets added to the `MultiDumpHandler`.
> Register `DumpRecorder` only once and keep original handler connected

- composer.json
- src/OriginFactory.php
I took a look at the backtrace and since it's using the debug_backtrace method from PHP itself and apparently $frame->class can be null there, I figured it's the best way to make this more robust and only look at the frames that have a class to begin with.
> Fix deprecated

- src/Watchers/ApplicationLogWatcher.php
This PR is a workaround for #237 
It isn't a real solution, but it solves the issue. And many of us are struggling with this for over six weeks.
> check if ApplicationLogPayload can be loaded

- src/Payloads/JobEventPayload.php
When `send_jobs_to_ray` is enabled and using the queue driver other than "sync". The package return an error "undefined payload()".
It would seem Laravel has done something, very odd, in my opinion. When using the sync/redis or sqs driver, Laravel creates an intermediate Job `\Illuminate\Queue\Jobs\SyncJob` which means the original job is inside it, but for other drivers (database) it directly returns the orignal job.
This PR has adds a check to retrieve the payload depending on the job received.
This fixes issue [586](https://github.com/spatie/ray/issues/586) of the package spatie/ray
Note: When a job is queued, three event are thrown `JobQueued`, `JobProcessing ` and `JobProcessed ` but only the first one will display the job. Whereas when using the sync driver, the two thrown events …
> Fix undefined payload when using queue driver other than sync

- composer.json
- src/Watchers/SlowQueryWatcher.php
- stub/ray.php
The slow query logging uses 500ms when manually activating via `ray()->slowQueries();`. When activated via the `ray.php` config `SEND_SLOW_QUERIES_TO_RAY` value, however, it defaults to 0ms causing all queries to be logged.
This adds a configurable `RAY_SLOW_QUERY_THRESHOLD=500` to the `ray.php` stub.
Additionally, the composer.json offered `format` script, but cs-fixer was not included in the dev dependencies.
> Feat: Slow query configuration

- stub/ray.php
This is a PR to just satisfy my own annoyance within the `ray.php` file. It lists options for Docker on Mac or Windows but not on Linux.
Now 172.17.0.1 won't work 100% of the time if you're doing custom networking with Docker, but by that point, you'll know to update that IP.
Feel free to dismiss this PR if it's irrelevant, it's more just to satisfy me.
> Added in comment to docblock for linux docker users

- src/DumpRecorder/DumpRecorder.php
- src/DumpRecorder/MultiDumpHandler.php
This PR fixes an issue with the dump handler not registering correctly on Laravel 9+.
I'm not sure if this is the best solution, but it is a solution.  Suggestions for improvements/alternatives are welcome.
> Fix broken tests for Laravel 9

- .github/dependabot.yml
- .github/workflows/dependabot-auto-merge.yml
- .github/workflows/php-cs-fixer.yml
- .github/workflows/phpstan.yml
- .github/workflows/run-tests.yml
- .github/workflows/update-changelog.yml
- README.md
- src/DumpRecorder/DumpRecorder.php
- src/DumpRecorder/MultiDumpHandler.php
This PR adds PHP 8.2 to the tests workflow and bumps the checkout action version to v3.
It also bumps the minimum required version of `nesbot/carbon` to enable PHP 8.2 support.
> Add PHP 8.2 Support

- src/Watchers/DuplicateQueryWatcher.php
- src/Watchers/QueryWatcher.php
- src/Watchers/SlowQueryWatcher.php
- tests/RayTest.php
Until now Ray did not work when the Laravel project did not use a DB connection (by disabling the DatabaseServiceProvider). That case resulted in a `Target class [db] does not exist.` exception. To solve this, checks are introduced to just ignore the DB watchers.
See: https://github.com/spatie/ray/discussions/771
> Make DB connection optional

- src/Watchers/ApplicationLogWatcher.php
The log context is not being passed to the `ApplicationLogPayload` class currently (relates to https://github.com/spatie/laravel-ray/discussions/162) and this PR simply passes that data.
Unfortunately it does **not** mean that the context is shown in Ray, because apparently the formatting of the 
Where is the formatting logic for the `Payload` subclasses? 🤔 is that somewhere in https://github.com/spatie/ray or the Electron app itself?
I propose that we show the message like we currently do, but that we add the context using the same formatter used for the `Spatie\Ray\Payloads\CarbonPayload` class or the `\Spatie\Ray\Payloads\TablePayload`
> Add context to ApplicationLogPayload

- src/Watchers/DuplicateQueryWatcher.php
- src/Watchers/QueryWatcher.php
- src/Watchers/SlowQueryWatcher.php
- additional improvements to #290
Internally, `DB::listen()` is equivalent to calling `app('db')->connection()->listen()` which initiate a database connection and cause issue such as nunomaduro/larastan#1588
> Avoid making DB connection unless necessary

- src/Payloads/ExecutedQueryPayload.php
- src/Payloads/QueryPayload.php
This pull request adds support for the newly added [raw SQL](https://github.com/laravel/framework/pull/47507) feature for Laravel 10.15. The implementation seems a bit verbose, but I couldn't think of another way to not introduce a breaking change.
**Before**
**After**
> feat: support raw sql

- src/Ray.php
- tests/Unit/QueryTest.php
This adds the ability to return the results of a callable rather than an instance of `Ray`. If the closure has a return type, assume that the results of the callable should be returned rather than `Ray`.
This started as #313 but did a little research and think this is a pretty elegant solution that gets the best of both worlds!
> Add ability to return the results of callable

- src/Ray.php
- It should shorten null coalescing operator and make it readable.
> Apply the shorten null coalescing operator

- src/DumpRecorder/MultiDumpHandler.php
- src/Payloads/CachePayload.php
- src/Payloads/MailablePayload.php
- src/Ray.php
Implicitly nullable parameter declarations are deprecated in PHP 8.4 ([ref](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)).
> Make implicit nullable param to explicit (PHP 8.4 compatibility)

- composer.json
Instead of having to update the branch alias for each release, the branch `main` can be an alias for all upcoming `1.x` versions.
> Update branch alias for version 1.x

- .github/workflows/run-tests.yml
- composer.json
- phpstan-baseline.neon
- phpstan.neon.dist
This PR resolves https://github.com/spatie/laravel-ray/issues/366
Currently anyone wishing to use PHPStan 2.0 / LaraStan 3.0 are unable to utilise the awesome sauce of Spatie Ray. This is related to package `rector/rector`, which currently no release tagged for PHPStan 2.0 yet. But it's in the testing phase see the open issue for more details https://github.com/rectorphp/rector/issues/8815#issuecomment-2493467044
Please note once the release has been tagged and released for `rector/rector` I will update this PR with the tags correctly for the `rector/rector` in the `composer.json` file.
I've also taken the feedback raised in https://github.com/spatie/laravel-ray/pull/364 and made changes to the `phpstan-baseline.neon` file.
Related PR: https://github.com/spatie/ray/pull/946
> Add support for PHPStan 2.0

- composer.json
- src/Commands/CleanRayCommand.php
- src/Support/Composer.php
> Install `rector/rector` during first run of `php artisan ray:clean` instead of requiring `rector/rector`

- stub/ray.php
Removes extra space in cache events comment to improve readability and prevent IDE warnings when using the stub file.
> Fix unnecessary consecutive spaces in comment
